### ISSUE TITLE
Center "Newsletter Signup:" text on homepage so it aligns with text in Email Address/SIGN UP bar; move "Newsletter Signup" text closer to Email Address bar  

### ISSUE THREAD

**Issue by evidenceaction2** [afterwire/evidenceaction#39]

**Comment by afterwire** [comment]
@evidenceaction2  Can I just confirm that this is what you are referring to here?
![newsletter-issue](https://user-images.githubusercontent.com/46914245/57052696-519eca80-6ccc-11e9-9f8c-2fa2f8111127.gif)

**Comment by evidenceaction2** [comment]
Yes, exactly.
