### ISSUE TITLE
Increase spacing between lines of headers on Deworm the World page (i.e. make spacing uniform with headers on Dispensers for Safe Water page)

### ISSUE THREAD

**Issue by evidenceaction2** [afterwire/evidenceaction#40]

**Comment by simonegiacco** [comment]
Need more details, can you be more specific?

**Comment by evidenceaction2** [comment]
![DtW header screenshot](https://user-images.githubusercontent.com/49215899/57091183-93347300-6cd6-11e9-898c-5fdc339d18cd.jpg)
![DSW header screenshot](https://user-images.githubusercontent.com/49215899/57091259-bf4ff400-6cd6-11e9-8683-aeeefe2383a8.jpg)

Here are two examples; the spacing between the two lines of text in the first screenshot of the Deworm the World page should match the spacing between the two lines in the second screenshot of the Dispensers for Safe Water page.
