### ISSUE TITLE
Quote Box Call Out on Deworm The World Page

### ISSUE THREAD

**Issue by afterwire** [afterwire/evidenceaction#7]
This is a question for @evidenceaction2 as per some of the feedback you provided in the original Google document.

There was a point in there where you said about the Deworm The World page

> In the first section, the size of the box with the quote appears to be too big and can take up fewer lines; also, the color of the vertical bar appears to be red and not the standard pink

So the section currently looks like this:
<img width="1081" alt="Screen Shot 2019-04-03 at 1 22 17 pm" src="https://user-images.githubusercontent.com/46914245/55448457-9115c080-5613-11e9-99bb-a3024183b895.png">

Would increasing the font size work for this section potentially? What do you think? Here is an example:
<img width="1045" alt="Screen Shot 2019-04-03 at 1 30 30 pm" src="https://user-images.githubusercontent.com/46914245/55448743-b6ef9500-5614-11e9-91cb-64bb0288248a.png">

I personally like the extra padding / spacing around the quote and think that it helps it stand out from a design point of view. However, I think using the same font size as everything else is obviously not doing us any favours from that point of view. Curious to hear your thoughts.

**Comment by simonegiacco** [comment]
![Screenshot 2019-04-05 00 47 12](https://user-images.githubusercontent.com/2013959/55593519-7a1ebd80-573c-11e9-8a13-417edd5d64b2.jpg)
